language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'

before_script:
  - npm prune

script:
  - scripts/build.sh
  # - scripts/test.sh

after_success:
  # - npm run coveralls
  # - scripts/deploy.sh
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
