language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '6.11.1'

before_script:
  - npm prune

script:
  # - scripts/test.sh
  - scripts/build.sh

after_success:
  # - npm run coveralls
  - scripts/deploy.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
