language: node_js

notifications:
  email: false

node_js:
  - '7'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
  - npm prune

script:
  - scripts/build.sh
  # - scripts/test.sh

after_success:
  # - npm run coveralls
  - scripts/deploy.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
